# RelayItToDiscord - Created by MrPowerGamerBR
# GitHub repo: https://github.com/MrPowerGamerBR/RelayItToDiscord

# This is the Discord Webhook link
# To get one, open your server configuration panel, go to "Webhooks", create a webhook and then
# copy the link to here. A (shortened, invalid) sample Webhook URI:
# https://discordapp.com/api/webhooks/46745878648/n-FqX6jROlA_oW51qhu
WebhookLink: "Webhook Link"

# This is the bot username on Discord
#
# For (almost) every string you can use these placeholders
# %player_name% = player name
# %player_displayname% = player display name
# %player_uuid% = player UUID
# %stripped_player_displayname% = player display name without color
# This has a limit of 32 chars! Anything above that will be cut off!
Username: "%player_name%"

# This is the chat format
# You can add fancy things to it if you want
# like the player's group!
# Or just keep it like that to just show the message
Format: "%content%"

# This is a alternative method of displaying messages and metadata in Discord
# First, We're going to name the "bot" with a static name with Username:
# Then, we're going to change the Format: to include the player's name.
#
# Uncomment the below two lines and comment out the above corrosponding lines to use.
#Username: "AeSixs Minion 1117"
#Format: "%player_name%: %content%"

# Should messages sent to Discord have their Minecraft colors removed?
StripColors: true

# This is the avatar used by the bot for the Minecraft player's chat.
# Use "https://minotar.net/helm/%player_name%/64.png" (as set by default)
# to allow each player's chat to be represented by their skin's head image. 
# Otherwise, you can set this to any image you prefer.  It is best to use 64px^2 images.
AvatarUrl: "https://minotar.net/helm/%player_name%/64.png"

# Use PlaceholderAPI? https://www.spigotmc.org/resources/placeholderapi.6245/
# Without PlaceholderAPI only the very basic placeholders will be available.
# These placeholders are usable if UsePlaceholderAPI is false:
# %player_uuid%, %player_name%, %player_displayname%, %stripped_player_displayname%
UsePlaceholderAPI: true

# Issues should never ever happen, but hey, nothing is perfect.
# So this is the advanced configuration section
Advanced:
    # If you are experiencing issues, change this value to false
    # Try editing this before editing the EventPriority
    IgnoreCancelled: true
