name: RelayItToDiscord
main: com.mrpowergamerbr.relayittodiscord.RelayItToDiscord
version: 1.0.0
softdepend: ["PlaceholderAPI"]
commands:
   relayreload:
      description: Reloads RelayItToDiscord
      usage: /<command>